/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceIndexRouteImport } from './routes/evidence.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as EvidenceCompareRouteImport } from './routes/evidence.compare'
import { Route as EvidenceExperimentIdRouteImport } from './routes/evidence.$experimentId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvidenceRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const EvidenceCompareRoute = EvidenceCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => EvidenceRoute,
} as any)
const EvidenceExperimentIdRoute = EvidenceExperimentIdRouteImport.update({
  id: '/$experimentId',
  path: '/$experimentId',
  getParentRoute: () => EvidenceRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/evidence/$experimentId': typeof EvidenceExperimentIdRoute
  '/evidence/compare': typeof EvidenceCompareRoute
  '/agents/': typeof AgentsIndexRoute
  '/evidence/': typeof EvidenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/evidence/$experimentId': typeof EvidenceExperimentIdRoute
  '/evidence/compare': typeof EvidenceCompareRoute
  '/agents': typeof AgentsIndexRoute
  '/evidence': typeof EvidenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/evidence': typeof EvidenceRouteWithChildren
  '/settings': typeof SettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/evidence/$experimentId': typeof EvidenceExperimentIdRoute
  '/evidence/compare': typeof EvidenceCompareRoute
  '/agents/': typeof AgentsIndexRoute
  '/evidence/': typeof EvidenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chat'
    | '/evidence'
    | '/settings'
    | '/agents/$agentId'
    | '/evidence/$experimentId'
    | '/evidence/compare'
    | '/agents/'
    | '/evidence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/settings'
    | '/agents/$agentId'
    | '/evidence/$experimentId'
    | '/evidence/compare'
    | '/agents'
    | '/evidence'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/chat'
    | '/evidence'
    | '/settings'
    | '/agents/$agentId'
    | '/evidence/$experimentId'
    | '/evidence/compare'
    | '/agents/'
    | '/evidence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ChatRoute: typeof ChatRoute
  EvidenceRoute: typeof EvidenceRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/evidence/compare': {
      id: '/evidence/compare'
      path: '/compare'
      fullPath: '/evidence/compare'
      preLoaderRoute: typeof EvidenceCompareRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/evidence/$experimentId': {
      id: '/evidence/$experimentId'
      path: '/$experimentId'
      fullPath: '/evidence/$experimentId'
      preLoaderRoute: typeof EvidenceExperimentIdRouteImport
      parentRoute: typeof EvidenceRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface EvidenceRouteChildren {
  EvidenceExperimentIdRoute: typeof EvidenceExperimentIdRoute
  EvidenceCompareRoute: typeof EvidenceCompareRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
}

const EvidenceRouteChildren: EvidenceRouteChildren = {
  EvidenceExperimentIdRoute: EvidenceExperimentIdRoute,
  EvidenceCompareRoute: EvidenceCompareRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
}

const EvidenceRouteWithChildren = EvidenceRoute._addFileChildren(
  EvidenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ChatRoute: ChatRoute,
  EvidenceRoute: EvidenceRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
